///import localFont from "next/font/local";
import "./styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Head from "next/head";

{
  /***************Font Zone*********************/
}
import { Playfair_Display } from "@next/font/google";

const playfair = Playfair_Display({
  weight: ["400"], // ระบุน้ำหนักของฟอนต์ที่ต้องการใช้
  subsets: ["latin"], // ระบุ subset ที่ต้องการใช้
});

{
  /***************Font Zone*********************/
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* เพิ่มฟอนต์จาก Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&family=Open+Sans:wght@400;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={`${playfair.className}`}>
        <link rel="icon" href="/images/favicon.png" type="image/png" />
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}

export const metadata = {
  title: "Touch of Yoga",
  description: "Generated by create next app",
  keywords: "ร้าน, นอน, ขายเครื่องประดับ",
};

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}*/
