///import localFont from "next/font/local";
import "./styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export default function RootLayout({ children }) {
  return (
      <html lang="en"> 
          <body>
              <Navbar />
              <main>{children}</main>
              <Footer />
          </body>
      </html>
  );
}

export const metadata = {
  title: "Touch of Yoga",
  description: "Generated by create next app",
  keywords: "ร้าน, นอน, ขายเครื่องประดับ"
};



/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}*/
